package com.daolv.forwordproxy.controller;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.io.IOException;

@RestController("/")
public class proxyXoso {

    @GetMapping()
    public String home(){
        return "ok";

    }


    @GetMapping("getketqua")
    public ResponseEntity<?> getXoSoPhp(@RequestParam ("type") String type) throws IOException {
        OkHttpClient client = new OkHttpClient().newBuilder()
                .build();
        Request request = new Request.Builder()
                .url("http://www.kqxs.vn/realtime.php?type="+type)
                .method("GET", null)
                .addHeader("Connection", "keep-alive")
                .addHeader("sec-ch-ua", "\"Google Chrome\";v=\"89\", \"Chromium\";v=\"89\", \";Not A Brand\";v=\"99\"")
                .addHeader("Accept", "text/html, */*; q=0.01")
                .addHeader("X-Requested-With", "XMLHttpRequest")
                .addHeader("sec-ch-ua-mobile", "?0")
                .addHeader("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36")
                .addHeader("Sec-Fetch-Site", "same-origin")
                .addHeader("Sec-Fetch-Mode", "cors")
                .addHeader("Sec-Fetch-Dest", "empty")
                .addHeader("Referer", "https://www.kqxs.vn/xo-so-truc-tuyen")
                .addHeader("Accept-Language", "vi,en;q=0.9,vi-VN;q=0.8,en-US;q=0.7")
                .addHeader("Cookie", "isGoogleRedirect=true; PHPSESSID=l99rljco9s6d30m3ofbisc9fbp; __utmc=243497887; __utmz=243497887.1616839393.2.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); __utma=243497887.403849119.1616676942.1616839393.1616921445.3; __utmt=1; __utmb=243497887.20.10.1616921445")
                .build();
        Response response = client.newCall(request).execute();
        String res = response.body().string();
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type",response.headers().get("Content-Type"));
        headers.add("Date",response.headers().get("Date"));
        res = res.replace("/images/loading_2.gif","https://www.kqxs.vn/images/loading_2.gif");

      //  String pattern = "(.*)( <div class=\"message-result\">a-z0-9_-\n/)(.*)";
        res = res.replaceAll("                    Soạn: <span class=\"highlight\">XSMB</span> gửi <span\n" +
                "                            class=\"highlight\">8110</span> nhận ngay kết quả <span\n" +
                "                            class=\"highlight\">Miền Bắc</span> sớm nhất!\n" +
                "                </div>","<div class=\"entry-content\">\n" +
                "    <p data-amp-original-style=\"text-align: center;\" class=\"amp-wp-cdd8ca0\"><span data-amp-original-style=\"font-size: 20pt; color: #ff0000;\" class=\"amp-wp-62d876d\"><strong>HƯỚNG DẪN CÁCH\n" +
                "                LẤY SỐ BẠCH THỦ LÔ VIP TỶ LỆ NỔ 100%</strong></span></p>\n" +
                "    <p data-amp-original-style=\"text-align: center;\" class=\"amp-wp-cdd8ca0\"><span data-amp-original-style=\"font-size: 16pt;\" class=\"amp-wp-5ff1f9a\">\n" +
                "            <amp-img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" alt=\"\uD83D\uDC49\" class=\"wp-smiley amp-wp-enforced-sizes amp-wp-843f19c i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout\" width=\"72\" height=\"72\" noloading=\"\" layout=\"intrinsic\" data-amp-original-style=\"height: 1em; max-height: 1em;\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\" lightbox=\"i-amphtml-auto-lightbox-0\" on=\"tap:amp-lightbox-gallery.activate\">\n" +
                "                <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzcyJyB3aWR0aD0nNzInIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZycgdmVyc2lvbj0nMS4xJy8+\">\n" +
                "                </i-amphtml-sizer><noscript><img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" alt=\"\uD83D\uDC49\" class=\"wp-smiley amp-wp-843f19c\" width=\"72\" height=\"72\" data-amp-original-style=\"height: 1em; max-height: 1em;\"></noscript><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "            </amp-img>&nbsp;<strong>Bấm vào</strong>&nbsp;<a href=\"https://www.google.com.vn/search?q=kubet+365\" target=\"_blank\" rel=\"nofollow noopener\" data-wpel-link=\"exclude\"><strong>KUBET</strong></a>&nbsp;\n" +
                "            <amp-img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" alt=\"\uD83D\uDC48\" class=\"wp-smiley amp-wp-enforced-sizes amp-wp-843f19c i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout\" width=\"72\" height=\"72\" noloading=\"\" layout=\"intrinsic\" data-amp-original-style=\"height: 1em; max-height: 1em;\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\" lightbox=\"i-amphtml-auto-lightbox-1\" on=\"tap:amp-lightbox-gallery.activate\">\n" +
                "                <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzcyJyB3aWR0aD0nNzInIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZycgdmVyc2lvbj0nMS4xJy8+\">\n" +
                "                </i-amphtml-sizer><noscript><img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" alt=\"\uD83D\uDC48\" class=\"wp-smiley amp-wp-843f19c\" width=\"72\" height=\"72\" data-amp-original-style=\"height: 1em; max-height: 1em;\"></noscript><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "            </amp-img> Hoặc ra Google gõ:&nbsp;<a href=\"https://www.google.com.vn/search?q=kubet365\" target=\"_blank\" rel=\"nofollow noopener\" data-wpel-link=\"exclude\"><strong>KUBET365</strong></a>\n" +
                "        </span></p>\n" +
                "    <p>\n" +
                "        <amp-img class=\"size-medium wp-image-6336 aligncenter amp-wp-enforced-sizes i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout amp-notsupported\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" alt=\"tìm kiếm kubet365\" width=\"800\" height=\"267\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" sizes=\"(max-width: 800px) 100vw, 800px\" layout=\"intrinsic\" disable-inline-width=\"\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\">\n" +
                "            <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzI2Nycgd2lkdGg9JzgwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJyB2ZXJzaW9uPScxLjEnLz4=\">\n" +
                "            </i-amphtml-sizer><noscript><img loading=\"lazy\" class=\"size-medium wp-image-6336 aligncenter\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" alt=\"tìm kiếm kubet365\" width=\"800\" height=\"267\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" sizes=\"(max-width: 800px) 100vw, 800px\"></noscript><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content i-amphtml-ghost\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "        </amp-img>\n" +
                "    </p>\n" +
                "</div>");
        res = res.replaceAll("                                    <div class=\"message-result\">\n" +
                "                        Soạn: <span class=\"highlight\">XSTN</span> gửi\n" +
                "                        <span\n" +
                "                                class=\"highlight\">8110</span> nhận ngay kết quả <span\n" +
                "                                class=\"highlight\">Tây Ninh</span> sớm nhất!\n" +
                "                    </div>","");
        res = res.replaceAll("                                        <div class=\"message-result\">\n" +
                "                        Soạn: <span class=\"highlight\">XSAG</span> gửi\n" +
                "                        <span\n" +
                "                                class=\"highlight\">8110</span> nhận ngay kết quả <span\n" +
                "                                class=\"highlight\">An Giang</span> sớm nhất!\n" +
                "                    </div>","");
        res = res.replaceAll("                                        <div class=\"message-result\">\n" +
                "                        Soạn: <span class=\"highlight\">XSBTH</span> gửi\n" +
                "                        <span\n" +
                "                                class=\"highlight\">8110</span> nhận ngay kết quả <span\n" +
                "                                class=\"highlight\">Bình Thuận</span> sớm nhất!\n" +
                "                    </div>","<div class=\"entry-content\">\n" +
                "    <p data-amp-original-style=\"text-align: center;\" class=\"amp-wp-cdd8ca0\"><span data-amp-original-style=\"font-size: 20pt; color: #ff0000;\" class=\"amp-wp-62d876d\"><strong>HƯỚNG DẪN CÁCH\n" +
                "                LẤY SỐ BẠCH THỦ LÔ VIP TỶ LỆ NỔ 100%</strong></span></p>\n" +
                "    <p data-amp-original-style=\"text-align: center;\" class=\"amp-wp-cdd8ca0\"><span data-amp-original-style=\"font-size: 16pt;\" class=\"amp-wp-5ff1f9a\">\n" +
                "            <amp-img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" alt=\"\uD83D\uDC49\" class=\"wp-smiley amp-wp-enforced-sizes amp-wp-843f19c i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout\" width=\"72\" height=\"72\" noloading=\"\" layout=\"intrinsic\" data-amp-original-style=\"height: 1em; max-height: 1em;\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\" lightbox=\"i-amphtml-auto-lightbox-0\" on=\"tap:amp-lightbox-gallery.activate\">\n" +
                "                <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzcyJyB3aWR0aD0nNzInIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZycgdmVyc2lvbj0nMS4xJy8+\">\n" +
                "                </i-amphtml-sizer><noscript><img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" alt=\"\uD83D\uDC49\" class=\"wp-smiley amp-wp-843f19c\" width=\"72\" height=\"72\" data-amp-original-style=\"height: 1em; max-height: 1em;\"></noscript><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "            </amp-img>&nbsp;<strong>Bấm vào</strong>&nbsp;<a href=\"https://www.google.com.vn/search?q=kubet+365\" target=\"_blank\" rel=\"nofollow noopener\" data-wpel-link=\"exclude\"><strong>KUBET</strong></a>&nbsp;\n" +
                "            <amp-img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" alt=\"\uD83D\uDC48\" class=\"wp-smiley amp-wp-enforced-sizes amp-wp-843f19c i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout\" width=\"72\" height=\"72\" noloading=\"\" layout=\"intrinsic\" data-amp-original-style=\"height: 1em; max-height: 1em;\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\" lightbox=\"i-amphtml-auto-lightbox-1\" on=\"tap:amp-lightbox-gallery.activate\">\n" +
                "                <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzcyJyB3aWR0aD0nNzInIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZycgdmVyc2lvbj0nMS4xJy8+\">\n" +
                "                </i-amphtml-sizer><noscript><img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" alt=\"\uD83D\uDC48\" class=\"wp-smiley amp-wp-843f19c\" width=\"72\" height=\"72\" data-amp-original-style=\"height: 1em; max-height: 1em;\"></noscript><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "            </amp-img> Hoặc ra Google gõ:&nbsp;<a href=\"https://www.google.com.vn/search?q=kubet365\" target=\"_blank\" rel=\"nofollow noopener\" data-wpel-link=\"exclude\"><strong>KUBET365</strong></a>\n" +
                "        </span></p>\n" +
                "    <p>\n" +
                "        <amp-img class=\"size-medium wp-image-6336 aligncenter amp-wp-enforced-sizes i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout amp-notsupported\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" alt=\"tìm kiếm kubet365\" width=\"800\" height=\"267\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" sizes=\"(max-width: 800px) 100vw, 800px\" layout=\"intrinsic\" disable-inline-width=\"\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\">\n" +
                "            <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzI2Nycgd2lkdGg9JzgwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJyB2ZXJzaW9uPScxLjEnLz4=\">\n" +
                "            </i-amphtml-sizer><noscript><img loading=\"lazy\" class=\"size-medium wp-image-6336 aligncenter\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" alt=\"tìm kiếm kubet365\" width=\"800\" height=\"267\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" sizes=\"(max-width: 800px) 100vw, 800px\"></noscript><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content i-amphtml-ghost\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "        </amp-img>\n" +
                "    </p>\n" +
                "</div>");
        res = res.replaceAll("                                    <div class=\"message-result\">\n" +
                "                        Soạn: <span class=\"highlight\">XSQB</span> gửi\n" +
                "                        <span\n" +
                "                                class=\"highlight\">8110</span> nhận ngay kết quả <span\n" +
                "                                class=\"highlight\">Quảng Bình</span> sớm nhất!\n" +
                "                    </div>","");
        res = res.replaceAll("                                        <div class=\"message-result\">\n" +
                "                        Soạn: <span class=\"highlight\">XSBDI</span> gửi\n" +
                "                        <span\n" +
                "                                class=\"highlight\">8110</span> nhận ngay kết quả <span\n" +
                "                                class=\"highlight\">Bình Định</span> sớm nhất!\n" +
                "                    </div>","");
        res = res.replaceAll("                                        <div class=\"message-result\">\n" +
                "                        Soạn: <span class=\"highlight\">XSQT</span> gửi\n" +
                "                        <span\n" +
                "                                class=\"highlight\">8110</span> nhận ngay kết quả <span\n" +
                "                                class=\"highlight\">Quảng Trị</span> sớm nhất!\n" +
                "                    </div>","<div class=\"entry-content\">\n" +
                "    <p data-amp-original-style=\"text-align: center;\" class=\"amp-wp-cdd8ca0\"><span data-amp-original-style=\"font-size: 20pt; color: #ff0000;\" class=\"amp-wp-62d876d\"><strong>HƯỚNG DẪN CÁCH\n" +
                "                LẤY SỐ BẠCH THỦ LÔ VIP TỶ LỆ NỔ 100%</strong></span></p>\n" +
                "    <p data-amp-original-style=\"text-align: center;\" class=\"amp-wp-cdd8ca0\"><span data-amp-original-style=\"font-size: 16pt;\" class=\"amp-wp-5ff1f9a\">\n" +
                "            <amp-img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" alt=\"\uD83D\uDC49\" class=\"wp-smiley amp-wp-enforced-sizes amp-wp-843f19c i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout\" width=\"72\" height=\"72\" noloading=\"\" layout=\"intrinsic\" data-amp-original-style=\"height: 1em; max-height: 1em;\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\" lightbox=\"i-amphtml-auto-lightbox-0\" on=\"tap:amp-lightbox-gallery.activate\">\n" +
                "                <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzcyJyB3aWR0aD0nNzInIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZycgdmVyc2lvbj0nMS4xJy8+\">\n" +
                "                </i-amphtml-sizer><noscript><img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" alt=\"\uD83D\uDC49\" class=\"wp-smiley amp-wp-843f19c\" width=\"72\" height=\"72\" data-amp-original-style=\"height: 1em; max-height: 1em;\"></noscript><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC49\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f449.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "            </amp-img>&nbsp;<strong>Bấm vào</strong>&nbsp;<a href=\"https://www.google.com.vn/search?q=kubet+365\" target=\"_blank\" rel=\"nofollow noopener\" data-wpel-link=\"exclude\"><strong>KUBET</strong></a>&nbsp;\n" +
                "            <amp-img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" alt=\"\uD83D\uDC48\" class=\"wp-smiley amp-wp-enforced-sizes amp-wp-843f19c i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout\" width=\"72\" height=\"72\" noloading=\"\" layout=\"intrinsic\" data-amp-original-style=\"height: 1em; max-height: 1em;\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\" lightbox=\"i-amphtml-auto-lightbox-1\" on=\"tap:amp-lightbox-gallery.activate\">\n" +
                "                <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzcyJyB3aWR0aD0nNzInIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZycgdmVyc2lvbj0nMS4xJy8+\">\n" +
                "                </i-amphtml-sizer><noscript><img src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" alt=\"\uD83D\uDC48\" class=\"wp-smiley amp-wp-843f19c\" width=\"72\" height=\"72\" data-amp-original-style=\"height: 1em; max-height: 1em;\"></noscript><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"\uD83D\uDC48\" src=\"https://s.w.org/images/core/emoji/13.0.1/72x72/1f448.png\" data-amp-original-style=\"height: 1em; max-height: 1em;\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "            </amp-img> Hoặc ra Google gõ:&nbsp;<a href=\"https://www.google.com.vn/search?q=kubet365\" target=\"_blank\" rel=\"nofollow noopener\" data-wpel-link=\"exclude\"><strong>KUBET365</strong></a>\n" +
                "        </span></p>\n" +
                "    <p>\n" +
                "        <amp-img class=\"size-medium wp-image-6336 aligncenter amp-wp-enforced-sizes i-amphtml-layout-intrinsic i-amphtml-layout-size-defined i-amphtml-element i-amphtml-built i-amphtml-layout amp-notsupported\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" alt=\"tìm kiếm kubet365\" width=\"800\" height=\"267\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" sizes=\"(max-width: 800px) 100vw, 800px\" layout=\"intrinsic\" disable-inline-width=\"\" i-amphtml-layout=\"intrinsic\" i-amphtml-auto-lightbox-visited=\"\">\n" +
                "            <i-amphtml-sizer class=\"i-amphtml-sizer\" slot=\"i-amphtml-svc\"><img alt=\"\" aria-hidden=\"true\" class=\"i-amphtml-intrinsic-sizer\" role=\"presentation\" src=\"data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9JzI2Nycgd2lkdGg9JzgwMCcgeG1sbnM9J2h0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnJyB2ZXJzaW9uPScxLjEnLz4=\">\n" +
                "            </i-amphtml-sizer><noscript><img loading=\"lazy\" class=\"size-medium wp-image-6336 aligncenter\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" alt=\"tìm kiếm kubet365\" width=\"800\" height=\"267\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" sizes=\"(max-width: 800px) 100vw, 800px\"></noscript><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content i-amphtml-ghost\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\"><img decoding=\"async\" alt=\"tìm kiếm kubet365\" sizes=\"(max-width: 800px) 100vw, 800px\" srcset=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg 800w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-768x256.jpg 768w, https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365.jpg 873w\" src=\"https://kubet365.net/wp-content/uploads/2021/03/tim-kubet365-800x267.jpg\" class=\"i-amphtml-fill-content i-amphtml-replaced-content\">\n" +
                "        </amp-img>\n" +
                "    </p>\n" +
                "</div>");
        System.out.println(res);
        ResponseEntity responseEntity = new ResponseEntity<>(res,headers, HttpStatus.OK);
        return responseEntity;
    }

}
